server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  file:
    upload-dir: uploads/resumes

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-1.5-flash
  endpoint-url: https://generativelanguage.googleapis.com/v1beta/models

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: WARN
    com.resumeiq: INFO
